In [1]:
from othello_rules import *
from othello_net import *
from tensorflow.python.framework import ops
from datetime import datetime
from example_states import *
from feature_extractor import *
from training_utils import *
import numpy as np

In [2]:
# Ræsum graphið fyrir tensorflow
ops.reset_default_graph()
graph, img_data, train_step, ground_truths, loss, pred_up, keep_prob, learn_rate, score_out = create_othello_net()
saver = tf.train.Saver()
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
init_op = tf.initialize_all_variables()
sess.run(init_op)
current_model = "models/othello_6.ckpt"
if os.path.isfile(current_model):
    saver.restore(sess, current_model)

In [3]:
board = ffo_endgame_45()
player = 1
print(board)
features = board_to_input(board, player)
input_batch = [features]

[[ 0.  0. -1. -1. -1. -1. -1.  0.]
 [ 0.  0. -1. -1. -1. -1.  0.  0.]
 [ 0.  1.  1.  1. -1. -1.  0.  0.]
 [ 0.  1.  1. -1. -1. -1. -1.  0.]
 [ 0.  1.  1. -1. -1. -1.  1.  0.]
 [ 1.  1.  1.  1. -1.  1.  1.  0.]
 [ 0.  0.  0. -1.  1. -1.  0.  0.]
 [ 0.  0. -1. -1. -1. -1. -1.  0.]]


In [5]:
prediction = sess.run(pred_up, feed_dict={img_data:input_batch,
                                        keep_prob:1.0})
np.set_printoptions(precision=2)
prediction = np.transpose(prediction[0])
prediction = np.transpose(prediction[1])
legal_moves = find_legal_moves(board, player)
cleaned_predictions = zero_illegal_moves(prediction, legal_moves)
i,j = np.unravel_index(cleaned_predictions.argmax(), cleaned_predictions.shape)
move_argmax = str((i+1) * 10 + (j+1))
print(cleaned_predictions)
print(move_argmax)

[[ 0.    0.04  0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.03  0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.07  0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.22]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.5   0.    0.    0.    0.04  0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]]
73
