In [1]:
from othello_rules import *
from othello_net import *
from tensorflow.python.framework import ops
from datetime import datetime
from example_states import *
from feature_extractor import *
from training_utils import *
import numpy as np


In [2]:
print("policy gradient example")
test = policy_gradient_example()
test = np.transpose(test)
print(test)



policy gradient example
[[-1. -1. -1.  0.  0. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1. -1. -1.  1.  1.  1.  1.]
 [ 1. -1. -1.  1. -1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.]]


In [6]:
from __future__ import print_function
from collections import deque
from tensorflow.python.framework import ops
from rl_reinforce import REINFORCEothello
from othello_net import *
from othello_rules import *
from feature_extractor import *
import os, random, sys
import tensorflow as tf
import time
from datetime import datetime
from example_states import *
from training_utils import *
from reinforcement_utils import *
import random
tf.logging.set_verbosity(tf.logging.FATAL)
np.set_printoptions(precision=2)
tf.reset_default_graph()
test = policy_gradient_example()
test = np.transpose(test)
tf_graph_1 = tf.Graph()
with tf_graph_1.as_default():
    img_1, train_step_1, adam_1, ground_truth_1, loss_1, pred_1, learn_rate_1, score_1, weights = create_example_graph()
sess_1 = tf.Session(graph=tf_graph_1)
features = [test]
features = np.transpose(features)
with sess_1.as_default():
    with tf_graph_1.as_default():
        rl_reinforce_1 = REINFORCEothello(sess_1, adam_1, learn_rate_1, loss_1, score_1, ground_truth_1, img_1)
        tf.global_variables_initializer().run()
        saver_1 = tf.train.Saver(tf.global_variables(), max_to_keep=9999)
        #model_1 = "supervised/models/layers8filters64.ckpt"
        #if os.path.isfile(model_1 + ".meta"):
        #    saver_1.restore(sess_1, model_1)
        #    print("loaded graph 1 as " + model_1)
prediction = sess_1.run(pred_1, feed_dict={img_1:[features]})
print(prediction)
board = test
player = -1
x = tf.Print(weights, [weights])
v = sess_1.run(weights)
print(v)
print(player)
sampled_move = sample_action(board, player, prediction)
label = move_to_label('15')
action = label
state = features
reward = 1
action = [action]
action = np.transpose(action)
print(tf.trainable_variables())
for roll in range(0, 2):
    rl_reinforce_1.storeRollout(state, action, reward)
rl_reinforce_1.updateModel()
v = sess_1.run(weights)
print(v)
prediction = sess_1.run(pred_1, feed_dict={img_1:[features]})
print(prediction)
board = test
player = -1
print(board)
sampled_move = sample_action(board, player, prediction)

[[[[ 0.53  0.47]
   [ 0.52  0.48]
   [ 0.42  0.58]
   [ 0.41  0.59]
   [ 0.46  0.54]
   [ 0.46  0.54]
   [ 0.46  0.54]
   [ 0.5   0.5 ]]

  [[ 0.54  0.46]
   [ 0.43  0.57]
   [ 0.42  0.58]
   [ 0.46  0.54]
   [ 0.43  0.57]
   [ 0.46  0.54]
   [ 0.46  0.54]
   [ 0.51  0.49]]

  [[ 0.55  0.45]
   [ 0.42  0.58]
   [ 0.57  0.43]
   [ 0.41  0.59]
   [ 0.48  0.52]
   [ 0.46  0.54]
   [ 0.46  0.54]
   [ 0.51  0.49]]

  [[ 0.55  0.45]
   [ 0.56  0.44]
   [ 0.48  0.52]
   [ 0.39  0.61]
   [ 0.46  0.54]
   [ 0.46  0.54]
   [ 0.56  0.44]
   [ 0.51  0.49]]

  [[ 0.55  0.45]
   [ 0.53  0.47]
   [ 0.53  0.47]
   [ 0.59  0.41]
   [ 0.57  0.43]
   [ 0.58  0.42]
   [ 0.53  0.47]
   [ 0.47  0.53]]

  [[ 0.54  0.46]
   [ 0.55  0.45]
   [ 0.54  0.46]
   [ 0.5   0.5 ]
   [ 0.54  0.46]
   [ 0.54  0.46]
   [ 0.57  0.43]
   [ 0.51  0.49]]

  [[ 0.54  0.46]
   [ 0.57  0.43]
   [ 0.56  0.44]
   [ 0.56  0.44]
   [ 0.56  0.44]
   [ 0.56  0.44]
   [ 0.56  0.44]
   [ 0.47  0.53]]

  [[ 0.5   0.5 ]
   [ 0.51  0.49]


In [ ]:
from __future__ import print_function
from collections import deque
from tensorflow.python.framework import ops
from rl_reinforce import REINFORCEothello
from othello_net import *
from othello_rules import *
from feature_extractor import *
import os, random, sys
import tensorflow as tf
import time
from datetime import datetime
from example_states import *
from training_utils import *
from reinforcement_utils import *
import random
tf.logging.set_verbosity(tf.logging.FATAL)
np.set_printoptions(precision=2)
tf.reset_default_graph()
test = policy_gradient_example()
test = np.transpose(test)
tf_graph_1 = tf.Graph()
with tf_graph_1.as_default():
    img_1, train_step_1, adam_1, ground_truth_1, loss_1, pred_1, learn_rate_1, score_1 = create_no_graph()
sess_1 = tf.Session(graph=tf_graph_1)
board = test
player = -1
features = board_to_input_c(board, player, ['11', '22', '33', '44'])
with sess_1.as_default():
    with tf_graph_1.as_default():
        rl_reinforce_1 = REINFORCEothello(sess_1, adam_1, learn_rate_1, loss_1, score_1, ground_truth_1, img_1)
        tf.global_variables_initializer().run()
        saver_1 = tf.train.Saver(tf.global_variables(), max_to_keep=9999)
        model_1 = "../supervised/models/layers8filters64.ckpt"
        if os.path.isfile(model_1 + ".meta"):
            saver_1.restore(sess_1, model_1)
            print("loaded graph 1 as " + model_1)
prediction = sess_1.run(pred_1, feed_dict={img_1:[features]})

print(board)
print(player)
sampled_move = sample_action(board, player, prediction)
print(sampled_move)
label = move_to_label('15')
action = label
state = features
reward = 1
action = [action]
action = np.transpose(action)
for roll in range(0, 1):
    rl_reinforce_1.storeRollout(state, action, reward)
rl_reinforce_1.updateModel()

prediction = sess_1.run(pred_1, feed_dict={img_1:[features]})
board = test
player = -1
print(board)
print(player)
sampled_move = sample_action(board, player, prediction)
print(sampled_move)

## 